### ISSUE TITLE
app-text/wgetpaste-2.28-r1 generates incorrect URLs (Gentoo)

### ISSUE THREAD

**Issue by Kreyren** [zlin/wgetpaste#10] opened 2019-01-07 22:27 UTC
As referenced on https://bugs.gentoo.org/674750

If i use `wgetpaste -l bash` on https://pastebin.com/raw/vNGc9vzw it generates  `https://codeload.github.com/PhoenicisOrg/phoenicis/tar.gz/v9999`

https://i.imgur.com/CTIfBhX.png 

Video: https://youtu.be/uV4A4vd-ZxQ

Reproducable: Always

**Comment by mjeveritt** [comment] 2021-03-31 22:46
I think this can be closed now, if #12 was merged?

**Comment by heirecka** [comment] 2021-06-02 12:38
Closing, feel free to re-open if the issue isn't fixed.

**Closed by heirecka** 2021-06-02 12:38 UTC
